<?php

/*
 * Helper functions
 *
 * Support functions for processing of search queries and indexing of articles
 *
 */

// Should the given snippet/word be filtered out of a search query/index?
function word_should_be_filtered($snippet = ''){
    $return = false;
    $snippet = (string)$snippet;
    $snippet = trim($snippet);
    if(strlen($snippet) > 2){
        $filterable_word_array = filterable_word_array();
        if(in_array(strtolower($snippet), $filterable_word_array)){
            $return = true;
        }
    } else {
        $return = true;
    }
    return $return;
}

// Get array of filterable words
function filterable_word_array(){
    return array(
        'dartmouth',
        'the',
        'be',
        'and',
        'of',
        'is',
        'a',
        'in',
        'to',
        'have',
        'has',
        'to',
        'it',
        'its',
        'i',
        'that',
        'for',
        'you',
        'he',
        'with',
        'on',
        'do',
        'say',
        'this',
        'they',
        'at',
        'but',
        'we',
        'his',
        'from',
        'that',
        'not',
        'by',
        'she',
        'or',
        'as',
        'what',
        'go',
        'their',
        'can',
        'who',
        'get',
        'if',
        'would',
        'her',
        'all',
        'my',
        'make',
        'about',
        'know',
        'will',
        'as',
        'up',
        'one',
        'time',
        'there',
        'year',
        'so',
        'think',
        'when',
        'which',
        'them',
        'some',
        'me',
        'people',
        'take',
        'out',
        'into',
        'just',
        'see',
        'him',
        'your',
        'come',
        'could',
        'now',
        'than',
        'like',
        'other',
        'how',
        'then',
        'its',
        'our',
        'two',
        'more',
        'these',
        'want',
        'way',
        'was',
        'look',
        'first',
        'also',
        'new',
        'because',
        'day',
        'more',
        'use',
        'no',
        'man',
        'find',
        'here',
        'thing',
        'give',
        'many',
        'well',
        'only',
        'those',
        'tell',
        'one',
        'very',
        'her',
        'even',
        'back',
        'any',
        'good',
        'woman',
        'through',
        'us',
        'life',
        'child',
        'there',
        'work',
        'down',
        'may',
        'after',
        'should',
        'call',
        'world',
        'over',
        'school',
        'still',
        'try',
        'in',
        'as',
        'last',
        'ask',
        'need',
        'too',
        'feel',
        'three',
        'when',
        'state',
        'never',
        'become',
        'between',
        'high',
        'really',
        'something',
        'most',
        'another',
        'much',
        'family',
        'own',
        'out',
        'leave'
    );
}